In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv(r"C:\Users\Aishwarya\Desktop\Datasets\cars.csv")
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [3]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [4]:
df.replace('?', np.nan, inplace=True)

In [5]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3               NaN  alfa-romero       gas  convertible   
1          3               NaN  alfa-romero       gas  convertible   
2          1               NaN  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
si = SimpleImputer()

df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder()

In [10]:
#Selecting Categorical columns

cat_cols = df.select_dtypes(object).columns

cat_cols

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [11]:
df[cat_cols] = oe.fit_transform(df[cat_cols])

In [12]:
df

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0            3              122.0   0.0        1.0         0.0           2.0   
1            3              122.0   0.0        1.0         0.0           2.0   
2            1              122.0   0.0        1.0         2.0           2.0   
3            2              164.0   1.0        1.0         3.0           1.0   
4            2              164.0   1.0        1.0         3.0           0.0   
..         ...                ...   ...        ...         ...           ...   
200         -1               95.0  21.0        1.0         3.0           2.0   
201         -1               95.0  21.0        1.0         3.0           2.0   
202         -1               95.0  21.0        1.0         3.0           2.0   
203         -1               95.0  21.0        0.0         3.0           2.0   
204         -1               95.0  21.0        1.0         3.0           2.0   

     engine-location  width  height  engine-type  engine-size  horsepower  \
0                0.0   64.1    48.8          0.0          130       111.0   
1                0.0   64.1    48.8          0.0          130       111.0   
2                0.0   65.5    52.4          5.0          152       154.0   
3                0.0   66.2    54.3          3.0          109       102.0   
4                0.0   66.4    54.3          3.0          136       115.0   
..               ...    ...     ...          ...          ...         ...   
200              0.0   68.9    55.5          3.0          141       114.0   
201              0.0   68.8    55.5          3.0          141       160.0   
202              0.0   68.9    55.5          5.0          173       134.0   
203              0.0   68.9    55.5          3.0          145       106.0   
204              0.0   68.9    55.5          3.0          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 15 columns]

In [13]:
#feature scaling

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [35]:
x = df.iloc[:,:-1]
y = df['price']

In [36]:
sc = StandardScaler()

x = sc.fit_transform(x)

In [37]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3, random_state=1)

# Linear Regression

In [38]:
lr = LinearRegression()

lr.fit(xtrain,ytrain)

ypred = lr.predict(xtest)

print('Training Accuracy: ', lr.score(xtrain,ytrain))
print('Testing Accuracy: ', lr.score(xtest,ytest))

Training Accuracy:  0.8504573774895474
Testing Accuracy:  0.7965566780397382


In [39]:
lr.coef_

array([   56.07400861,    48.39390193, -1252.52182092,  -184.75278941,
        -145.88866308,  1036.72639753,  1970.96992814,  1689.40021497,
         884.01337611,   297.95302576,  4086.3172007 ,  -426.4324209 ,
        2010.17555652, -2864.80162677])

- Training Accuracy is high - Low bias
- Testing Accuarcy is low - High variance.

**Overfitting**

# Ridge Regression

In [40]:
rg = Ridge(alpha=10)
rg.fit(xtrain,ytrain)
rgpred = rg.predict(xtest)

print('Training Accuracy: ', rg.score(xtrain,ytrain))
print('Testing Accuracy: ', rg.score(xtest,ytest))

Training Accuracy:  0.844705971649782
Testing Accuracy:  0.8090124333137608


In [41]:
rg.coef_

array([  -97.42219182,    39.01774323, -1178.93577768,  -427.87716367,
        -256.72536309,  1008.04235933,  1741.20335144,  1584.2521081 ,
         889.00698675,   369.51429426,  3415.87703201,   105.52553432,
         231.52302995, -1229.50614652])

# Lasso Regression

In [42]:
ls = Lasso()
ls.fit(xtrain,ytrain)
lspred = ls.predict(xtest)

print('Training Accuracy: ', ls.score(xtrain,ytrain))
print('Testing Accuracy: ', ls.score(xtest,ytest))

Training Accuracy:  0.8504558834782978
Testing Accuracy:  0.7968051526874578


In [43]:
ls.coef_

array([   53.19425108,    46.53995077, -1251.31704488,  -187.28981318,
        -145.68836212,  1035.1514439 ,  1968.27005254,  1687.30899191,
         882.24697527,   297.11381145,  4085.51142718,  -424.63918835,
        1970.2111122 , -2827.58554588])

# Selection of alpha

In [45]:
for i in range(50,100):
    rg = Ridge(alpha=i)
    rg.fit(xtrain,ytrain)
    y = rg.predict(xtest)
    
    print(f"{i} {rg.score(xtrain,ytrain)} {rg.score(xtest,ytest)}")

50 0.8210202675646218 0.8001572442693232
51 0.8204618085475143 0.7997449481542974
52 0.8199042867085053 0.7993295224095756
53 0.819347672574628 0.7989111150548578
54 0.8187919381886071 0.7984898652683314
55 0.8182370570317002 0.7980659040533987
56 0.8176830039499918 0.7976393548456788
57 0.817129755084098 0.7972103340664384
58 0.8165772878022212 0.7967789516278836
59 0.8160255806364689 0.7963453113951322
60 0.8154746132223399 0.7959095116091375
61 0.8149243662412685 0.7954716452743648
62 0.8143748213661108 0.795031800514603
63 0.8138259612094572 0.7945900608999281
64 0.8132777692746445 0.7941465057475157
65 0.8127302299093517 0.7937012103987114
66 0.8121833282616542 0.7932542464745236
67 0.8116370502384196 0.7928056821114753
68 0.8110913824659298 0.7923555821795594
69 0.8105463122526164 0.7919040084838641
70 0.8100018275537989 0.7914510199512851
71 0.8094579169383238 0.7909966728035938
72 0.8089145695570016 0.7905410207180211
73 0.8083717751127463 0.7900841149763926
74 0.80782952383232

In [52]:
for i in range(450,500):
    ls = Lasso(alpha=i)
    ls.fit(xtrain,ytrain)
    y = ls.predict(xtest)
    
    print(f"{i} {ls.score(xtrain,ytrain)} {ls.score(xtest,ytest)}")

450 0.826495459777952 0.8036044671547998
451 0.8264278793532984 0.8035604699693127
452 0.8263601489219581 0.8035163324259695
453 0.8262922684839309 0.8034720545247707
454 0.8262242380392166 0.8034276362657157
455 0.8261560575689033 0.8033830776815429
456 0.8260877270188918 0.8033383788653713
457 0.8260192464617911 0.8032935396911636
458 0.8259506158976013 0.8032485601589195
459 0.8258818353263225 0.8032034402686394
460 0.8258129047479545 0.8031581800203232
461 0.8257438241624974 0.8031127794139707
462 0.825674593569951 0.8030672384495823
463 0.8256052129703156 0.8030215571271575
464 0.8255356823635911 0.8029757354466966
465 0.8254660017497774 0.8029297734081995
466 0.8253961711288746 0.8028836710116662
467 0.8253261905008826 0.8028374282570968
468 0.8252560598658015 0.8027910451444913
469 0.8251857792236313 0.8027445216738496
470 0.825115348574372 0.8026978578451717
471 0.8250447679180235 0.8026510536584577
472 0.8249740372545858 0.8026041091137075
473 0.8249031565840591 0.802557024210