In [1]:
!pip install bioinfokit

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv(r"D:\dataset\Wine.csv")
df.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [4]:
from sklearn.manifold import TSNE
from bioinfokit.visuz import cluster

In [5]:
x = df.iloc[:,:-1]
x

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 13 columns]

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
tsne = TSNE(n_components=2)
score = tsne.fit_transform(x)
score

array([[  5.254997  , -10.699653  ],
       [  5.748371  , -10.063413  ],
       [  6.6063347 , -12.490015  ],
       [  7.969169  , -15.001996  ],
       [  1.207723  ,  -2.9819524 ],
       [  7.632833  , -14.975427  ],
       [  6.9235315 , -13.986658  ],
       [  7.5770583 , -13.77272   ],
       [  5.1499166 , -10.211586  ],
       [  5.1471486 , -10.21494   ],
       [  7.791031  , -15.25855   ],
       [  6.830742  , -13.835403  ],
       [  7.1672325 , -14.247696  ],
       [  6.3355637 , -11.920617  ],
       [  7.9897738 , -15.328954  ],
       [  7.374866  , -14.062712  ],
       [  7.492799  , -13.509099  ],
       [  6.1346745 , -11.585791  ],
       [  8.069145  , -15.573862  ],
       [  2.9573133 ,  -5.8405914 ],
       [  1.9878803 ,  -4.220816  ],
       [  2.000928  ,  -3.7896755 ],
       [  5.0423303 , -10.004696  ],
       [  4.9873776 ,  -9.6176    ],
       [  2.8304396 ,  -5.9549766 ],
       [  2.7710552 ,  -5.3917537 ],
       [  6.6488376 , -12.667193  ],
 

In [9]:
cluster.tsneplot(score, colorlist=df['Customer_Segment'], figname="Wine_t-SNE")

# Diabetes Dataset

In [10]:
df = pd.read_csv(r"D:\dataset\diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [11]:
tsne = TSNE(n_components=2)
model = tsne.fit_transform(df.iloc[:,:-1])
model

array([[-29.880531  ,  -0.06522568],
       [-11.986039  ,  -4.0879645 ],
       [-39.153004  ,  -3.7742994 ],
       ...,
       [ 24.446783  ,   6.975148  ],
       [-28.75854   , -12.680367  ],
       [-13.4789    ,  -3.0148342 ]], dtype=float32)

In [13]:
cluster.tsneplot(model, colorlist=df['Outcome'], figname='Diabetes_t-SNE')

# Iris Dataset

In [15]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
                 header=None)
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
tsne = TSNE(n_components=2)
model = tsne.fit_transform(df.iloc[:,:-1])
model

array([[-23.611702 ,  10.089279 ],
       [-21.105064 ,   9.046296 ],
       [-21.186293 ,  10.187362 ],
       [-20.764452 ,   9.781459 ],
       [-23.761559 ,   9.79566  ],
       [-25.623129 ,   9.734678 ],
       [-21.346037 ,  10.572695 ],
       [-22.99371  ,   9.706161 ],
       [-20.021988 ,   9.809314 ],
       [-21.650875 ,   9.293126 ],
       [-25.059715 ,  10.335419 ],
       [-22.433823 ,   9.274111 ],
       [-20.869028 ,   9.277591 ],
       [-19.900421 ,  10.386554 ],
       [-26.27064  ,  10.623719 ],
       [-26.532549 ,  10.1326885],
       [-25.681154 ,  10.200215 ],
       [-23.708931 ,   9.909932 ],
       [-25.757885 ,  10.67189  ],
       [-24.812407 ,   9.538914 ],
       [-24.369915 ,  10.836553 ],
       [-24.478966 ,   9.4723835],
       [-21.47657  ,  11.338653 ],
       [-23.435173 ,   8.744777 ],
       [-22.58002  ,   8.404304 ],
       [-21.581211 ,   8.67268  ],
       [-23.320261 ,   9.131568 ],
       [-24.03713  ,  10.133366 ],
       [-23.582657 ,

In [18]:
cluster.tsneplot(model, colorlist=df[4], figname='iris_data_t-SNE')